/**
 * Generates the route table in `docs/reference/api.md`.
 *
 * Run with:
 *   npm run api:docs          regenerate the table
 *   npm run api:docs:check    fail if the committed table is stale
 *
 * Hand-writing 80+ endpoints produces a document that is wrong within a month.
 * Method, path and required role are all derivable from the source, so they are
 * derived here and the result is checked in CI.
 *
 * The required role is resolved by calling the real `requiredRoleForRequest`
 * from `src/lib/auth-policy.ts`. It is deliberately not reimplemented: a second
 * copy of the authorization rules would be a security-relevant divergence
 * waiting to happen.
 *
 * Only the block between the BEGIN/END markers is generated. Prose written
 * around it survives regeneration.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { requiredRoleForRequest, ANONYMOUS_PATHS } from "../src/lib/auth-policy";

const APP_ROOT = resolve(__dirname, "..");
const DOC_PATH = resolve(APP_ROOT, "../../docs/reference/api.md");
const ROUTE_PREFIX = "src/app/(dashboard)";

const BEGIN = "<!-- BEGIN GENERATED ROUTES -->";
const END = "<!-- END GENERATED ROUTES -->";

const HTTP_METHODS = [
  "GET",
  "POST",
  "PUT",
  "PATCH",
  "DELETE",
  "HEAD",
  "OPTIONS",
] as const;

interface Route {
  path: string;
  group: string;
  methods: string[];
  usesFilters: boolean;
  /** "yes" = falls back to mock; "always" = never queries a real source; "—" = no mock path. */
  mock: "yes" | "always" | "—";
}

/**
 * `git ls-files` rather than a glob: the routes live under a parenthesised Next.js
 * route group, `src/app/(dashboard)/api/`, and the parentheses defeat glob tooling.
 */
function discoverRouteFiles(): string[] {
  return execFileSync("git", ["ls-files", "src/app"], {
    cwd: APP_ROOT,
    encoding: "utf8",
  })
    .split("\n")
    .map((f) => f.trim())
    .filter((f) => f.endsWith("/route.ts") && f.startsWith(`${ROUTE_PREFIX}/api/`))
    .sort();
}

function toRoutePath(file: string): string {
  return file.slice(ROUTE_PREFIX.length).replace(/\/route\.ts$/, "");
}

function exportedMethods(source: string): string[] {
  return HTTP_METHODS.filter((m) => {
    const fn = new RegExp(`export\\s+(?:async\\s+)?function\\s+${m}\\b`);
    const cn = new RegExp(`export\\s+const\\s+${m}\\s*[:=]`);
    return fn.test(source) || cn.test(source);
  });
}

/**
 * Distinguishes a route that *falls back* to mock data from one that is *always*
 * mock. The second kind returns `isMock: true` unconditionally and never reaches a
 * real data source, which is exactly the sort of thing a reader needs told
 * explicitly rather than discovered in production.
 */
function mockKind(source: string): Route["mock"] {
  if (/isMockMode/.test(source)) return "yes";
  if (/isMock:\s*true/.test(source)) return "always";
  return "—";
}

function buildRoutes(): Route[] {
  return discoverRouteFiles().map((file) => {
    const source = readFileSync(join(APP_ROOT, file), "utf8");
    const path = toRoutePath(file);
    const segments = path.split("/").filter(Boolean); // ["api", "<group>", ...]
    return {
      path,
      group: segments[1] ?? "root",
      methods: exportedMethods(source),
      usesFilters: /filterSchema/.test(source),
      mock: mockKind(source),
    };
  });
}

/** Display form: Next.js `[date]` reads better as `{date}` in prose. */
function displayPath(path: string): string {
  return path.replace(/\[([^\]]+)\]/g, "{$1}");
}

function roleFor(route: Route, method: string): string {
  if (ANONYMOUS_PATHS.some((p) => route.path === p || route.path.startsWith(`${p}/`))) {
    return "Anonymous";
  }
  return requiredRoleForRequest(route.path, method);
}

function render(routes: Route[]): string {
  const groups = new Map<string, Route[]>();
  for (const r of routes) {
    const list = groups.get(r.group) ?? [];
    list.push(r);
    groups.set(r.group, list);
  }

  const lines: string[] = [];
  lines.push("");
  lines.push(
    `_${routes.length} endpoints across ${groups.size} groups. Generated by \`npm run api:docs\` — do not edit by hand._`,
  );
  lines.push("");

  for (const group of Array.from(groups.keys()).sort()) {
    const list = groups.get(group)!.sort((a, b) => a.path.localeCompare(b.path));
    lines.push(`### \`/api/${group}\``);
    lines.push("");
    lines.push("| Endpoint | Method | Role | Filters | Mock |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const r of list) {
      const methods = r.methods.length ? r.methods : ["—"];
      for (const m of methods) {
        const role = m === "—" ? "—" : roleFor(r, m);
        lines.push(
          `| \`${displayPath(r.path)}\` | ${m} | ${role} | ${r.usesFilters ? "yes" : "—"} | ${r.mock} |`,
        );
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}

function main(): void {
  const check = process.argv.includes("--check");
  const doc = readFileSync(DOC_PATH, "utf8");

  const start = doc.indexOf(BEGIN);
  const end = doc.indexOf(END);
  if (start === -1 || end === -1) {
    console.error(`Markers ${BEGIN} / ${END} not found in ${DOC_PATH}`);
    process.exit(1);
  }

  const next =
    doc.slice(0, start + BEGIN.length) + "\n" + render(buildRoutes()) + doc.slice(end);

  if (check) {
    if (next !== doc) {
      console.error(
        "docs/reference/api.md is out of date with the routes in src/app.\n" +
          "Run `npm run api:docs` in apps/finops-dashboard and commit the result.",
      );
      process.exit(1);
    }
    console.log("OK: docs/reference/api.md matches the routes in src/app.");
    return;
  }

  writeFileSync(DOC_PATH, next);
  console.log(`Wrote ${DOC_PATH}`);
}

main();
