import type {
  ReservationRow,
  ReservationTrendPoint,
  ReservationFilterOptions,
} from "../types";

export const mockReservationDetail: ReservationRow[] = [
  {
    commitmentName: "VM_Reserved_D4s_v5_3yr",
    commitmentId: "/providers/Microsoft.Capacity/reservationOrders/abc-001",
    commitmentType: "Reservation",
    term: "3 Year",
    resourceType: "Microsoft.Compute/virtualMachines",
    upfrontPaid: 34200.0,
    consumed: 28500.0,
    used: 27075.0,
    unused: 1425.0,
    utilization: 95.0,
    days: 30,
  },
  {
    commitmentName: "SQL_Reserved_vCore_8_1yr",
    commitmentId: "/providers/Microsoft.Capacity/reservationOrders/abc-002",
    commitmentType: "Reservation",
    term: "1 Year",
    resourceType: "Microsoft.Sql/servers",
    upfrontPaid: 18600.0,
    consumed: 15200.0,
    used: 12920.0,
    unused: 2280.0,
    utilization: 85.0,
    days: 30,
  },
  {
    commitmentName: "Compute_SavingsPlan_$500_3yr",
    commitmentId:
      "/providers/Microsoft.BillingBenefits/savingsPlanOrders/sp-001",
    commitmentType: "SavingsPlan",
    term: "3 Year",
    resourceType: "Microsoft.Compute",
    upfrontPaid: 0.0,
    consumed: 14800.0,
    used: 14060.0,
    unused: 740.0,
    utilization: 95.0,
    days: 30,
  },
  {
    commitmentName: "CosmosDB_Reserved_400RU_1yr",
    commitmentId: "/providers/Microsoft.Capacity/reservationOrders/abc-003",
    commitmentType: "Reservation",
    term: "1 Year",
    resourceType: "Microsoft.DocumentDb/databaseAccounts",
    upfrontPaid: 9600.0,
    consumed: 8200.0,
    used: 5740.0,
    unused: 2460.0,
    utilization: 70.0,
    days: 30,
  },
  {
    commitmentName: "Redis_Reserved_C3_3yr",
    commitmentId: "/providers/Microsoft.Capacity/reservationOrders/abc-004",
    commitmentType: "Reservation",
    term: "3 Year",
    resourceType: "Microsoft.Cache/Redis",
    upfrontPaid: 7200.0,
    consumed: 6100.0,
    used: 4575.0,
    unused: 1525.0,
    utilization: 75.0,
    days: 30,
  },
  {
    commitmentName: "General_SavingsPlan_$200_1yr",
    commitmentId:
      "/providers/Microsoft.BillingBenefits/savingsPlanOrders/sp-002",
    commitmentType: "SavingsPlan",
    term: "1 Year",
    resourceType: "Microsoft.Compute",
    upfrontPaid: 0.0,
    consumed: 5800.0,
    used: 5568.0,
    unused: 232.0,
    utilization: 96.0,
    days: 30,
  },
];

export const mockReservationTrend: ReservationTrendPoint[] = [
  { month: "2025-01-01", used: 62000, unused: 8200 },
  { month: "2025-02-01", used: 65400, unused: 7100 },
  { month: "2025-03-01", used: 64800, unused: 8660 },
  { month: "2025-04-01", used: 69863, unused: 8662 },
];

export const mockReservationFilterOptions: ReservationFilterOptions = {
  commitmentNames: [
    "VM_Reserved_D4s_v5_3yr",
    "SQL_Reserved_vCore_8_1yr",
    "Compute_SavingsPlan_$500_3yr",
    "CosmosDB_Reserved_400RU_1yr",
    "Redis_Reserved_C3_3yr",
    "General_SavingsPlan_$200_1yr",
  ],
  resourceTypes: [
    "Microsoft.Compute/virtualMachines",
    "Microsoft.Sql/servers",
    "Microsoft.Compute",
    "Microsoft.DocumentDb/databaseAccounts",
    "Microsoft.Cache/Redis",
  ],
  commitmentTypes: ["Reservation", "SavingsPlan"],
};
