import type { SkuAdvisorPayload } from "../sku-advisor-contract";

/**
 * Bundled sample of an Azure SKU Advisor run.
 *
 * Fully synthetic: the subscription, cluster and workload names below do not
 * belong to any customer, and the prices are illustrative. It exists so the
 * `/sku-advisor` view renders in mock mode like every other page, and so the
 * selectors have a stable fixture to be tested against.
 */
export const mockSkuAdvisorPayload: SkuAdvisorPayload = {
  generated_at: "2026-01-15T12:00:00Z",
  summary: {
    currency: "USD",
    os_type: "mixed",
    savings_threshold_pct: 10,
    pricing_basis: "retail",
    workloads_evaluated: 42,
    recommendations_count: 6,

    total_current_monthly: 48250.4,
    total_projected_monthly: 39118.6,
    total_monthly_savings: 9131.8,
    total_annual_savings: 109581.6,
    effective_savings_rate_pct: 18.9,
    esr_scope: {
      estate_esr_pct: 18.9,
      addressable_esr_pct: 18.9,
      addressable_share_pct: 100,
      estate_current_monthly: 48250.4,
      addressable_current_monthly: 48250.4,
    },

    savings_by_track: {
      rightsizing: {
        track: "rightsizing",
        label: "SKU swap",
        monthly_savings: 5320.4,
        workloads: 4,
      },
      decommission: {
        track: "decommission",
        label: "Decommission or power off",
        monthly_savings: 1240.0,
        workloads: 3,
      },
      storage: {
        track: "storage",
        label: "Managed disk",
        monthly_savings: 1180.6,
        workloads: 5,
      },
      schedule: {
        track: "schedule",
        label: "Scheduled shutdown",
        monthly_savings: 1390.8,
        workloads: 7,
      },
    },

    quota_blocked_workloads: 1,
    quota_blocked_monthly_savings: 612.0,
    capacity_checked_workloads: 6,
    capacity_available_count: 4,
    capacity_restricted_count: 1,
    capacity_not_offered_count: 0,
    capacity_quota_blocked_count: 1,
    capacity_unknown_count: 0,

    lifecycle_retiring_workloads: 2,
    lifecycle_retiring_vms: 14,
    lifecycle_retiring_monthly: 7420.5,
    lifecycle_previous_gen_workloads: 3,
    lifecycle_previous_gen_vms: 21,
    lifecycle_previous_gen_monthly: 11380.2,
    lifecycle_retiring_targets: 0,
    lifecycle_retiring_target_vms: 0,
    lifecycle_exposure: [
      {
        series: "Dv3-series",
        status: "announced",
        retirement_date: "2027-03-31",
        vms: 12,
        current_monthly: 3120.0,
        source: "curated",
        live_confirmed: false,
      },
      {
        series: "Esv4-series",
        status: "previous_gen",
        retirement_date: "",
        vms: 6,
        current_monthly: 4180.2,
        source: "curated",
        live_confirmed: false,
      },
      {
        series: "Bms-series",
        status: "previous_gen",
        retirement_date: "",
        vms: 9,
        current_monthly: 1180.4,
        source: "curated",
        live_confirmed: false,
      },
    ],
    lifecycle_catalog_source: "bundled-sample",
    lifecycle_source: "bundled-sample",

    disks: {
      evaluated: true,
      source: "offline-sample",
      monthly_savings: 1180.6,
      annual_savings: 14167.2,
      counted_in_total_monthly: 1180.6,
      deferred_to_other_track_monthly: 0,
    },
    idle: {
      evaluated: true,
      source: "offline-sample",
      monthly_savings: 1240.0,
      annual_savings: 14880.0,
      counted_in_total_monthly: 1240.0,
      deferred_to_other_track_monthly: 0,
    },
    commitment: {
      evaluated: false,
      reason:
        "Active reservations and savings plans were not read in this run, so commitment coverage was not evaluated.",
      monthly_savings: 0,
      annual_savings: 0,
    },
    spot: {
      evaluated: true,
      source: "offline-sample",
      monthly_savings: 0,
      annual_savings: 0,
      counted_in_total_monthly: 0,
      deferred_to_other_track_monthly: 0,
    },
    schedule: {
      evaluated: true,
      source: "offline-sample",
      monthly_savings: 1620.4,
      annual_savings: 19444.8,
      counted_in_total_monthly: 1390.8,
      deferred_to_other_track_monthly: 229.6,
    },
  },
  recommendations: [
    {
      current_size: "Standard_D8s_v5",
      recommended_size: "Standard_D8as_v6",
      region: "eastus",
      count: 8,
      current_monthly: 2592.96,
      recommended_monthly: 1985.6,
      monthly_savings: 607.36,
      annual_savings: 7288.32,
      savings_pct: 23.42,
      status: "recommended",
      track: "rightsizing",
      headline:
        "Standard_D8as_v6 is 23.4% cheaper than Standard_D8s_v5 at the same vCPU and memory.",
      workload_type: "AKS",
      os_type: "Linux",
      cluster: "aks-platform-prod",
      power_state: "running",
      architecture: "AMD",
      compat_risk: "low",
      compat_note: "AMD (x86-64): binary-compatible; validate performance.",
      actionability: "cluster-level",
      is_new_sku: true,
      quota_ok: true,
      capacity: { status: "available" },
      lifecycle: {
        current: { status: "current" },
        target: { status: "current" },
      },
    },
    {
      current_size: "Standard_E16s_v4",
      recommended_size: "Standard_E16s_v5",
      region: "eastus",
      count: 6,
      current_monthly: 4180.2,
      recommended_monthly: 3568.2,
      monthly_savings: 612.0,
      annual_savings: 7344.0,
      savings_pct: 14.64,
      status: "recommended",
      track: "rightsizing",
      headline:
        "Standard_E16s_v5 replaces a previous-generation SKU at a lower price.",
      workload_type: "VM",
      os_type: "Linux",
      power_state: "running",
      architecture: "Intel",
      compat_risk: "low",
      actionability: "vm-level",
      is_new_sku: true,
      quota_ok: false,
      quota_required_cores: 96,
      quota_available_cores: 32,
      quota_note:
        "Target family ESv5 has 32 of the 96 cores required in eastus. Request a quota increase first.",
      capacity: { status: "quota_blocked" },
      lifecycle: {
        current: {
          status: "previous_gen",
          series: "Esv4",
          retirement_date: "",
          replacement: "Standard_E16s_v5",
        },
        target: { status: "current" },
      },
    },
    {
      current_size: "Standard_D4s_v3",
      recommended_size: "Standard_D4as_v6",
      region: "westeurope",
      count: 12,
      current_monthly: 3120.0,
      recommended_monthly: 2246.4,
      monthly_savings: 873.6,
      annual_savings: 10483.2,
      savings_pct: 28.0,
      status: "recommended",
      track: "rightsizing",
      headline:
        "Standard_D4s_v3 is retiring; Standard_D4as_v6 is the supported replacement and costs less.",
      workload_type: "VM",
      os_type: "Windows",
      power_state: "running",
      architecture: "AMD",
      compat_risk: "low",
      actionability: "vm-level",
      is_new_sku: true,
      quota_ok: true,
      capacity: { status: "available" },
      lifecycle: {
        current: {
          status: "retiring",
          series: "Dv3",
          retirement_date: "2027-03-31",
          days_remaining: 440,
          replacement: "Standard_D4as_v6",
          migration_guide:
            "https://learn.microsoft.com/azure/virtual-machines/sizes",
        },
        target: { status: "current" },
      },
    },
    {
      current_size: "Standard_F8s_v2",
      recommended_size: "Standard_F8als_v6",
      region: "brazilsouth",
      count: 4,
      current_monthly: 1428.8,
      recommended_monthly: 1142.0,
      monthly_savings: 286.8,
      annual_savings: 3441.6,
      savings_pct: 20.07,
      status: "recommended",
      track: "rightsizing",
      headline:
        "Compute-optimized swap at equivalent vCPU count, restricted in this region.",
      workload_type: "VM",
      os_type: "Linux",
      power_state: "running",
      architecture: "AMD",
      compat_risk: "medium",
      actionability: "vm-level",
      is_new_sku: true,
      quota_ok: true,
      capacity: {
        status: "restricted",
        note: "SKU offered in brazilsouth but restricted for this subscription.",
      },
      lifecycle: {
        current: { status: "current" },
        target: { status: "current" },
      },
    },
    {
      current_size: "Standard_D2s_v3",
      recommended_size: "",
      region: "eastus",
      count: 6,
      current_monthly: 1240.0,
      recommended_monthly: 0,
      monthly_savings: 1240.0,
      annual_savings: 14880.0,
      savings_pct: 100,
      status: "stopped",
      track: "decommission",
      headline:
        "Six VMs are stopped but still allocated, so compute is billed with no workload running.",
      workload_type: "VM",
      os_type: "Linux",
      power_state: "stopped",
      compat_risk: "none",
      actionability: "vm-level",
      quota_ok: true,
      capacity: { status: "available" },
      lifecycle: {
        current: { status: "current" },
        target: { status: "current" },
      },
    },
    {
      current_size: "Standard_B4ms",
      recommended_size: "Standard_B4as_v2",
      region: "eastus2",
      count: 9,
      current_monthly: 1180.4,
      recommended_monthly: 940.3,
      monthly_savings: 240.1,
      annual_savings: 2881.2,
      savings_pct: 20.34,
      status: "recommended",
      track: "rightsizing",
      headline: "Burstable v2 generation at a lower price for the same profile.",
      workload_type: "VM",
      os_type: "Linux",
      power_state: "running",
      architecture: "AMD",
      compat_risk: "low",
      actionability: "vm-level",
      is_new_sku: true,
      quota_ok: true,
      capacity: { status: "available" },
      lifecycle: {
        current: {
          status: "previous_gen",
          series: "Bms",
          replacement: "Standard_B4as_v2",
        },
        target: { status: "current" },
      },
    },
  ],
};
