"use client";

import { useState, useEffect, useCallback } from "react";
import { useDailyInsightsGenerate } from "@/hooks/useDailyInsights";

export default function DailyInsightsPage() {
  const { report, isGenerating, error, generate } = useDailyInsightsGenerate();
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [historicalContent, setHistoricalContent] = useState<string | null>(
    null,
  );
  const [history, setHistory] = useState<
    Array<{ date: string; generatedAt: string; preview: string }>
  >([]);

  const refreshHistory = useCallback(() => {
    fetch("/api/daily-insights/history")
      .then((r) => r.json())
      .then((d) => setHistory(d.data || []))
      .catch(() => {});
  }, []);

  useEffect(() => {
    refreshHistory();
  }, [report, refreshHistory]);

  useEffect(() => {
    generate(false);
  }, [generate]);

  const loadHistorical = async (date: string) => {
    setSelectedDate(date);
    setHistoricalContent(null);
    try {
      const res = await fetch(`/api/daily-insights/${date}`);
      if (!res.ok) return;
      const data = await res.json();
      if (data.report) {
        setHistoricalContent(data.report.content);
      }
    } catch {
      // ignore
    }
  };

  const clearSelection = () => {
    setSelectedDate(null);
    setHistoricalContent(null);
  };

  const displayContent = selectedDate ? historicalContent : report?.content;
  const generatedAt = selectedDate ? undefined : report?.generatedAt;
  const tokens = selectedDate ? undefined : report?.tokens;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-white">Daily Insights</h1>
          <p className="mt-1 text-sm text-slate-400">
            Daily executive report generated by AI — updated at 08:00 UTC
          </p>
        </div>
        <div className="flex items-center gap-3">
          {generatedAt && (
            <span className="text-xs text-slate-500">
              Generated: {new Date(generatedAt).toLocaleString("en-US")}
            </span>
          )}
          <button
            onClick={() => {
              clearSelection();
              generate(true);
            }}
            disabled={isGenerating}
            className="flex items-center gap-2 rounded-lg bg-sky-500 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-sky-400 disabled:opacity-50"
          >
            {isGenerating ? (
              <>
                <svg
                  className="h-4 w-4 animate-spin"
                  viewBox="0 0 24 24"
                  fill="none"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  />
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                  />
                </svg>
                Generating...
              </>
            ) : (
              <>
                <svg
                  className="h-4 w-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                  />
                </svg>
                Regenerate
              </>
            )}
          </button>
        </div>
      </div>

      {error && (
        <div className="rounded-lg border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-400">
          ⚠️ {error}
        </div>
      )}

      {selectedDate && (
        <div className="flex items-center gap-2 rounded-lg border border-sky-500/20 bg-sky-500/10 px-4 py-2 text-sm text-sky-300">
          <span>
            Viewing report for{" "}
            {new Date(selectedDate + "T00:00:00").toLocaleDateString("en-US")}
          </span>
          <button
            onClick={clearSelection}
            className="ml-auto text-sky-400 hover:text-white"
          >
            ← Back to current
          </button>
        </div>
      )}

      <div className="grid grid-cols-4 gap-6">
        {/* Main Report */}
        <div className="col-span-3">
          {isGenerating && !displayContent ? (
            <div className="flex flex-col items-center justify-center rounded-2xl border border-white/10 bg-navy-800 p-12">
              <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-sky-500/10">
                <svg
                  className="h-8 w-8 animate-spin text-sky-400"
                  viewBox="0 0 24 24"
                  fill="none"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  />
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                  />
                </svg>
              </div>
              <p className="mt-4 text-sm font-medium text-white">
                Generating report...
              </p>
              <p className="mt-1 text-xs text-slate-400">
                Querying ADX and Azure OpenAI. This can take up to 60 seconds.
              </p>
            </div>
          ) : displayContent ? (
            <div>
              <ReportRenderer content={displayContent} />
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center rounded-2xl border border-white/10 bg-navy-800 p-12 text-center">
              <p className="text-sm text-slate-400">
                No report available.
              </p>
              <button
                onClick={() => generate(true)}
                className="mt-3 rounded-lg bg-sky-500 px-4 py-2 text-sm text-white hover:bg-sky-400"
              >
                Generate now
              </button>
            </div>
          )}

          {tokens && (
            <div className="mt-3 flex items-center gap-4 text-xs text-slate-500">
              <span>Tokens: {tokens.total.toLocaleString()}</span>
              <span>Prompt: {tokens.prompt.toLocaleString()}</span>
              <span>Completion: {tokens.completion.toLocaleString()}</span>
            </div>
          )}
        </div>

        {/* History Sidebar */}
        <div className="col-span-1">
          <div className="rounded-2xl border border-white/10 bg-navy-800 p-4">
            <h3 className="text-sm font-semibold text-white">History</h3>
            <div className="mt-3 space-y-2">
              {history.length === 0 ? (
                <p className="text-xs text-slate-500">
                  No previous reports.
                </p>
              ) : (
                history.slice(0, 14).map((h) => (
                  <button
                    key={h.date}
                    onClick={() => loadHistorical(h.date)}
                    className={`w-full rounded-lg px-3 py-2 text-left text-xs transition-colors ${
                      selectedDate === h.date
                        ? "bg-sky-500/10 text-sky-400"
                        : "text-slate-400 hover:bg-white/5 hover:text-white"
                    }`}
                  >
                    <div className="font-medium">
                      {new Date(h.date + "T00:00:00").toLocaleDateString(
                        "en-US",
                        { day: "2-digit", month: "short", year: "numeric" },
                      )}
                    </div>
                    <div className="mt-0.5 truncate text-slate-500">
                      {new Date(h.generatedAt).toLocaleTimeString("en-US", {
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </div>
                  </button>
                ))
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function ReportRenderer({ content }: { content: string }) {
  const sections = splitIntoSections(content);

  return (
    <div className="space-y-6">
      {sections.map((section, i) => {
        if (section.type === "title") {
          return (
            <div key={i} className="border-b border-white/10 pb-4">
              <h1 className="text-xl font-bold text-white">{section.text}</h1>
            </div>
          );
        }
        if (section.type === "section") {
          return (
            <div
              key={i}
              className="rounded-xl border border-white/10 bg-navy-900/50 overflow-hidden"
            >
              <div className="border-b border-white/10 bg-white/[0.02] px-5 py-3">
                <h2 className="text-base font-semibold text-white">
                  {section.heading}
                </h2>
              </div>
              <div className="px-5 py-4 space-y-2">
                <SectionBody lines={section.lines} />
              </div>
            </div>
          );
        }
        if (section.type === "footer") {
          return (
            <div
              key={i}
              className="border-t border-white/10 pt-3 text-center text-xs text-slate-500 italic"
            >
              {section.text}
            </div>
          );
        }
        return null;
      })}
    </div>
  );
}

type Section =
  | { type: "title"; text: string }
  | { type: "section"; heading: string; lines: string[] }
  | { type: "footer"; text: string };

function splitIntoSections(content: string): Section[] {
  const lines = content.split("\n");
  const sections: Section[] = [];
  let current: Section | null = null;

  for (const line of lines) {
    if (line.startsWith("# ") && !line.startsWith("## ")) {
      if (current) sections.push(current);
      current = null;
      sections.push({ type: "title", text: line.slice(2).trim() });
      continue;
    }
    if (line.startsWith("## ")) {
      if (current) sections.push(current);
      current = { type: "section", heading: line.slice(3).trim(), lines: [] };
      continue;
    }
    if (line.trim() === "---") {
      if (current) sections.push(current);
      current = null;
      continue;
    }
    if (
      !current &&
      line.startsWith("*") &&
      line.endsWith("*") &&
      !line.startsWith("**")
    ) {
      sections.push({
        type: "footer",
        text: line.replace(/^\*+|\*+$/g, "").trim(),
      });
      continue;
    }
    if (current && current.type === "section") {
      current.lines.push(line);
    } else if (line.trim()) {
      if (!current) {
        current = { type: "section", heading: "", lines: [] };
      }
      if (current.type === "section") current.lines.push(line);
    }
  }
  if (current) sections.push(current);
  return sections;
}

function SectionBody({ lines }: { lines: string[] }) {
  const groups = groupContent(lines);

  return (
    <>
      {groups.map((group, i) => {
        if (group.type === "table")
          return <MarkdownTable key={i} rows={group.rows} />;
        if (group.type === "code") {
          return (
            <div key={i} className="overflow-x-auto rounded-lg bg-navy-900 p-4">
              {group.lang && (
                <div className="mb-1 text-[10px] uppercase tracking-wider text-slate-500">
                  {group.lang}
                </div>
              )}
              <pre className="text-xs text-emerald-400">
                <code>{group.code}</code>
              </pre>
            </div>
          );
        }
        return (
          <div key={i}>
            {group.lines.map((line, j) => (
              <MarkdownLine key={j} line={line} />
            ))}
          </div>
        );
      })}
    </>
  );
}

type ContentGroup =
  | { type: "table"; rows: string[] }
  | { type: "code"; lang: string; code: string }
  | { type: "text"; lines: string[] };

function groupContent(lines: string[]): ContentGroup[] {
  const groups: ContentGroup[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (line.startsWith("```")) {
      const lang = line.slice(3).trim();
      const codeLines: string[] = [];
      i++;
      while (i < lines.length && !lines[i].startsWith("```")) {
        codeLines.push(lines[i]);
        i++;
      }
      i++;
      groups.push({ type: "code", lang, code: codeLines.join("\n") });
      continue;
    }

    if (line.startsWith("|") && line.endsWith("|")) {
      const tableRows: string[] = [];
      while (
        i < lines.length &&
        lines[i].startsWith("|") &&
        lines[i].endsWith("|")
      ) {
        tableRows.push(lines[i]);
        i++;
      }
      groups.push({ type: "table", rows: tableRows });
      continue;
    }

    const lastGroup = groups[groups.length - 1];
    if (lastGroup && lastGroup.type === "text") {
      lastGroup.lines.push(line);
    } else {
      groups.push({ type: "text", lines: [line] });
    }
    i++;
  }
  return groups;
}

function MarkdownTable({ rows }: { rows: string[] }) {
  const parsed = rows
    .filter((r) => !r.replace(/[|\s-:]/g, "").length === false)
    .filter((r) => !/^\|[\s-:|]+\|$/.test(r))
    .map((r) =>
      r
        .split("|")
        .filter((_, ci, arr) => ci > 0 && ci < arr.length - 1)
        .map((c) => c.trim()),
    );

  if (parsed.length === 0) return null;
  const header = parsed[0];
  const body = parsed.slice(1);

  return (
    <div className="overflow-x-auto rounded-lg border border-white/10">
      <table className="w-full text-sm">
        <thead>
          <tr className="bg-white/[0.04]">
            {header.map((cell, i) => (
              <th
                key={i}
                className={`px-4 py-2.5 text-xs font-semibold uppercase tracking-wider text-slate-400 ${
                  i === 0 ? "text-left" : "text-right"
                }`}
              >
                {cell}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-white/5">
          {body.map((row, ri) => (
            <tr key={ri} className="transition-colors hover:bg-white/[0.02]">
              {row.map((cell, ci) => (
                <td
                  key={ci}
                  className={`px-4 py-2.5 ${
                    ci === 0
                      ? "font-medium text-slate-200 text-left"
                      : "text-right text-slate-300"
                  }`}
                >
                  {renderInline(cell)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function MarkdownLine({ line }: { line: string }) {
  if (!line.trim()) return <div className="h-1.5" />;

  if (line.startsWith("### "))
    return (
      <h3 className="mt-2 text-sm font-semibold text-sky-300">
        {line.slice(4)}
      </h3>
    );

  if (line.startsWith("- ") || line.startsWith("* "))
    return (
      <div className="flex gap-2 py-0.5 text-sm text-slate-300">
        <span className="mt-0.5 text-sky-400">•</span>
        <span>{renderInline(line.slice(2))}</span>
      </div>
    );

  if (/^\d+\.\s/.test(line)) {
    const match = line.match(/^(\d+)\.\s(.*)$/);
    if (match)
      return (
        <div className="flex gap-2 py-0.5 text-sm text-slate-300">
          <span className="mt-0.5 min-w-[1.2rem] text-right text-sky-400">
            {match[1]}.
          </span>
          <span>{renderInline(match[2])}</span>
        </div>
      );
  }

  if (line.startsWith("> "))
    return (
      <blockquote className="border-l-2 border-sky-500/40 pl-3 py-1 text-sm italic text-slate-400">
        {renderInline(line.slice(2))}
      </blockquote>
    );

  return (
    <p className="text-sm text-slate-300 leading-relaxed">
      {renderInline(line)}
    </p>
  );
}

function renderInline(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);
  return parts.map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return (
        <strong key={i} className="font-semibold text-white">
          {part.slice(2, -2)}
        </strong>
      );
    }
    if (part.startsWith("`") && part.endsWith("`")) {
      return (
        <code
          key={i}
          className="rounded bg-navy-900 px-1 py-0.5 text-xs text-emerald-400"
        >
          {part.slice(1, -1)}
        </code>
      );
    }
    return part;
  });
}
